language: php

env: BITCOINLIB_EXTENSIVE_TESTING=true

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

install:
 - "composer update"

script:
 - ./vendor/bin/phpunit -c ./build/
 - ./vendor/bin/phpcs --standard=./build/phpcs.xml -n -a ./src/
